oped:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50


#   # Position Controllers ---------------------------------------
#   lf_hip_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lf_hip_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   lf_upper_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lf_upper_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   lf_lower_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lf_lower_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}

#   lh_hip_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lh_hip_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   lh_upper_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lh_upper_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   lh_lower_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: lh_lower_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}

#   rf_hip_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rf_hip_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   rf_upper_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rf_upper_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   rf_lower_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rf_lower_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}

#   rh_hip_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rh_hip_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   rh_upper_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rh_upper_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}
#   rh_lower_leg_joint_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: rh_lower_leg_joint
#     pid: {p: 100.0, i: 0, d: 0.0}

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
    #   type: effort_controllers/JointPositionController
      joints:
          - lf_hip_joint
          - lf_upper_leg_joint
          - lf_lower_leg_joint
          - rf_hip_joint
          - rf_upper_leg_joint
          - rf_lower_leg_joint
          - lh_hip_joint
          - lh_upper_leg_joint
          - lh_lower_leg_joint
          - rh_hip_joint
          - rh_upper_leg_joint
          - rh_lower_leg_joint

      gains:
        # lf_hip_joint        : {p: 180, d: 0.9, i: 20}
        # lf_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
        # lf_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
        # rf_hip_joint        : {p: 180, d: 0.9, i: 20}
        # rf_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
        # rf_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
        # lh_hip_joint        : {p: 180, d: 0.9, i: 20}
        # lh_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
        # lh_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
        # rh_hip_joint        : {p: 180, d: 0.9, i: 20}
        # rh_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
        # rh_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
        lf_hip_joint        : {p: 100, d: 0, i: 0.01}
        lf_upper_leg_joint  : {p: 100, d: 0, i: 0.01}
        lf_lower_leg_joint  : {p: 100, d: 0, i: 0.01}
        rf_hip_joint        : {p: 100, d: 0, i: 0.01}
        rf_upper_leg_joint  : {p: 100, d: 0, i: 0.01}
        rf_lower_leg_joint  : {p: 100, d: 0, i: 0.01}
        lh_hip_joint        : {p: 100, d: 0, i: 0.01}
        lh_upper_leg_joint  : {p: 100, d: 0, i: 0.01}
        lh_lower_leg_joint  : {p: 100, d: 0, i: 0.01}
        rh_hip_joint        : {p: 100, d: 0, i: 0.01}
        rh_upper_leg_joint  : {p: 100, d: 0, i: 0.01}
        rh_lower_leg_joint  : {p: 100, d: 0, i: 0.01}